---
- hosts: all
  tasks: 
  - name: Install build-essential
    package:
      name: build-essential
      state: latest
    become: true

  - name: BASH bashrc
    template:
      src: bashrc
      dest: ~/.bashrc
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Install GIT
    package:
      name: git
      state: latest
    become: true

  - name: GIT gitconfig
    template:
      src: gitconfig
      dest: ~/.gitconfig
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Install VIM
    package:
      name: vim
      state: latest
    become: true

  - name: VIM vimrc
    template:
      src: vimrc
      dest: ~/.vimrc
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Install Ruby
    package:
      name: ruby-full
      state: latest
    become: true

  - name: Install Bundler
    gem:
      name: bundler
      state: latest
      user_install: true

  - name: Install Jekyll
    gem:
      name: jekyll
      state: latest
      user_install: true

  - name: Install NGINX
    notify: restart nginx
    package:
      name: nginx
      state: latest
    become: true

  - name: Install FCGIWRAP
    notify:
    - restart fcgiwrap.socket
    package:
      name: fcgiwrap
      state: latest
    become: true

  - name: Install CGIT
    notify: restart nginx
    package:
      name: cgit
      state: latest
    become: true

  - name: CGIT cgitrc
    notify:
    - restart nginx
    template:
      src: cgitrc
      dest: /etc/cgitrc
      owner: root
      group: root
      mode: 0644
    become: true

  - name: CGIT config
    notify:
    - restart nginx
    - restart fcgiwrap.socket
    template:
      src: cgit
      dest: /etc/nginx/sites-available/cgit
      owner: root
      group: root
      mode: 0644
    become: true

  - name: CGIT enable
    notify: restart nginx
    file:
      src: /etc/nginx/sites-available/cgit
      dest: /etc/nginx/sites-enabled/cgit
      owner: root
      group: root
      state: link
    become: true

  - name: REPO jjg1914.me-ansible.git
    git:
      repo: git@github.com:jjg1914/jjg1914.me-ansible.git
      dest: /home/ubuntu/git/jjg1914.me-ansible/

  - name: REPO jjg1914.me
    git:
      repo: https://github.com/jjg1914/jjg1914.me
      dest: /home/ubuntu/git/jjg1914.me/
    notify: rebuild jjg1914.me

  - name: jjg1914.me config
    notify:
    - restart nginx
    template:
      src: jjg1914.me
      dest: /etc/nginx/sites-available/jjg1914.me
      owner: root
      group: root
      mode: 0644
    become: true

  - name: CGIT enable
    notify: restart nginx
    file:
      src: /etc/nginx/sites-available/jjg1914.me
      dest: /etc/nginx/sites-enabled/default
      owner: root
      group: root
      state: link
    become: true

  handlers:	

  - name: restart nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
    become: true

  - name: restart fcgiwrap.socket
    service:
      name: fcgiwrap.socket
      state: restarted
      enabled: yes
    become: true

  - name: rebuild jjg1914.me
    shell: bundle install && bundle exec jekyll build chdir=/home/ubuntu/git/jjg1914.me
